### ISSUE TITLE
Release v0.3.3

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#208]
There are a few things left to do before the maintenance release v0.3.3. I marked them in the milestone:

 - [x] Fix Pillow 3.0.0 compatibility (#204)
 - [x] Fix plots_to_frame - tp.annotate3d compatibility (#206)
 - [ ] Rebuild tifffile and PyAV conda packages for numpy 1.10
 - [x] Make `pims.open` also list `FramesSequenceND` subclasses
 - [x] Display slicerator dependency in docs (#201, #209)
 - [x] Update release notes + other docwork if necessary
 - [x] Release slicerator 0.9.5

 Are there any other things that should go into v0.3.3? @danielballan @tacaswell

**Comment by danielballan** [comment]
That looks right. I am not aware of a direct issue with numpy 1.10. We need to rebuilt tifffile and PyAV conda packages though. Is there anything else?

**Comment by caspervdw** [comment]
Ok I edited the list and made a PR for the dependency list. If you can rebuild the packages, then we should run Travis with numpy 1.10 to check for any issues.

**Comment by caspervdw** [comment]
In the readme it is stated:

"If you are using Windows, I recommend 32-bit Anaconda even if your system is 64-bit. (One of the optional dependencies is not yet compatible with 64-bit Python.)" 

I have been using 64bit on windows with no problems. Only with PyAv. Which dependency are you referring to?

**Comment by danielballan** [comment]
Ha, that goes back to when I was using OpenCV's bindings to FFmpeg to read in videos, before PyAV existed. I'll open a PR to clean it out.

**Comment by caspervdw** [comment]
We actually should clean the readme completely like in trackpy and just refer to the docs. Double documentation is more likely to get outdated...

**Comment by caspervdw** [comment]
I think #211 and #223 are the only PRs that need to go in before 0.3.3. Does any of you want to review them? @danielballan @nkeim @tacaswell

**Comment by nkeim** [comment]
Both look fine to me. I had enough to do with #211 that someone else should probably merge it.

On Jan 10, 2016, at 2:05 PM, Casper van der Wel <notifications@github.com<mailto:notifications@github.com>> wrote:


I think #211<https://github.com/soft-matter/pims/pull/211> and #223<https://github.com/soft-matter/pims/pull/223> are the only PRs that need to go in before 0.3.3. Does any of you want to review them? @danielballan<https://github.com/danielballan> @nkeim<https://github.com/nkeim> @tacaswell<https://github.com/tacaswell>

**Comment by caspervdw** [comment]
Almost there! Just #224 should go in so that Travis passes and then I think we are ready for v0.3.3

**Comment by caspervdw** [comment]
I tested the docs locally, some minor things came out that I fixed in #225. Also the release notes are updated.
If you all agree with the release, who has the time to do it?

**Comment by caspervdw** [comment]
@danielballan got me access to PyPi. Just for safety, could one of you checkout v0.3.3rc1 before I tag v0.3.3?  @tacaswell  @nkeim 

It passes on the trackpy Travis so I guess everything is OK: https://travis-ci.org/caspervdw/trackpy/builds/106545223

**Comment by nkeim** [comment]
I'm on it.

**Comment by nkeim** [comment]
Clean Python 3 environment, then

```
conda install nose trackpy
conda remove pims
conda remove slicerator
pip install [rc zipfile url]
conda install jinja2  # Note this was necessary for pims tests to run
```

Checked out release candidate and trackpy/master and ran nosetests for both packages. All pass, though in the trackpy tests I did get lots of warnings like this:

```./Users/nkeim/anaconda/envs/pimstest/lib/python3.5/site-packages/PIL/Image.py:1151: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/nkeim/projects/trackpy/trackpy/trackpy/tests/video/image_sequence/T76S3F00001.png'>
  self.load()
```

Anyhow, looks good to go up on PyPI.

**Comment by caspervdw** [comment]
Thanks @nkeim! I'll just wait for someone to check on #226, don't want to merge my own PR right before the release.

Those warnings are probably generated by the trackpy tests. We should track them down.

**Comment by caspervdw** [comment]
Done! @danielballan  do you have time to send out the conda packages?

**Comment by danielballan** [comment]
Done. Packages of slicerator 0.9.7 and pims 0.3.3 for Python 2.7, 3.3, 3.4, 3.5 are on the soft-matter channel.

**Comment by caspervdw** [comment]
@danielballan Super! The docs still have to be built. I could give it a go but I don't have write access to the doc repo.

**Comment by tacaswell** [comment]
@caspervdw You should have write permissions now.

**Comment by caspervdw** [comment]
Thanks @tacaswell  I pushed the newly built docs. They aren't visible on http://soft-matter.github.io/pims/ yet but I guess that will take some time to update.

We do need some kind of menu to navigate through doc versions. And someone needs to look into the Travis automatic build of the docs. I'll make an issue for that.
