### ISSUE TITLE
Release version v0.4

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims#253]
It's been almost a year since the last release, and there have been some additions to PIMS. What do we want to get into v0.4?  @tacaswell @danielballan @nkeim 

API breaks
~~- [ ] clean the `as_gray`, `dtype` and `process_func` kwargs (#250)~~
~~- [ ] start implementing default pipelines (#247)~~
- [x] Finish the video exporters (#257)

New readers
- [x] imageio/moviepy (#233)
- [x] readersequence, single images (#249)

Performance
- [x] nd-flexibility (#227)

Docs
- [x] Docs and release notes (#261)

**Comment by danielballan** [comment]
I have some (yet unpushed) branched where I've been exploring how PIMS might interface with dask. I think that could affect our thinking on the future of the pipeline decorator and the defaults we want to ship. My preference is to wait on API breaks until we have a clearer plan there.

On the other hand, I haven't been giving PIMS very much of my bandwidth recently, so if you want to forge ahead for now and worry about dask integration later, I'll happily defer.

**Comment by caspervdw** [comment]
Hey @danielballan, dask integration is a fantastic idea! I did look into dask a while ago and I recall that it might replace the slicerator/pipeline infrastructure that we developed.

So it makes sense waiting for that before we go crazy on the pipelines.

I guess that dropping the kwargs is something that we will do anyway. We should supply a good alternative, which in this case might be 2 appropriate `pipeline` functions (as_grey, as_dtype). and an explanation how to implement `process_func` using a pipeline.

What would a dask-equivalent look like? We could already work the API in that direction.

I will probably be spending less and less time on pims/trackpy the coming months. Do you think you have the bandwidth to implement this dask-rebase?

**Comment by danielballan** [comment]
Yeah, I can easily justify that as a day-job activity. I'll post my work so far as is later this week.

**Comment by caspervdw** [comment]
Ok I am very curious on this! Tagging my coworker @rbnvrw because he may be interested in this dask-based lazy processing.

**Comment by danielballan** [comment]
@caspervdw Would you like to tag 0.4 as is for pimsviewer's sake? I think dask compatibility will require more than just #254 and I don't want to hold you up.

**Comment by caspervdw** [comment]
Yes especially #227 and the new readers would be great to have in a release. Then we leave the kwarg cleaning, pipelines and/or dask implementation for 0.5?

**Comment by danielballan** [comment]
That sounds right. Which new readers? (Sorry if that's a dumb question, I'm a bit bleary at the moment.) Are there any PRs left to be merged in 0.4?

**Comment by caspervdw** [comment]
The ImageReader, ImageIO, Moviepy, PyAV, wrappers, and the sequence of FramesSequenceND reader (ReaderSequence).

I guess we only need some docs and release notes before the release. Also, maybe a revision of the pyav export function.

**Comment by danielballan** [comment]
Oh, you mean the readers that have already been merged since the last tag, not any additional ones. OK, I'm caught up. :sheep:

OK, it sounds like between us we can crank this out this week then?

**Comment by caspervdw** [comment]
Yup, just pushed #257 to finish the exporters. Only todo is now the docs.

**Comment by caspervdw** [comment]
I also finished the docs. #261 

- Could one of you check and merge #257?
- Do you agree with postponing the rest of the v0.4 milestones?

**Comment by danielballan** [comment]
I think v0.4 is good to go. @tacaswell, speak up if you disagree.

**Comment by caspervdw** [comment]
Ok! I am starting the release now
