### ISSUE TITLE
Release v0.5

### ISSUE THREAD

**Issue by nkeim** [soft-matter/pims#342]
pims v0.4.1 was released in 2017. Support for some formats, especially still images, continues to work great in that release, but there have been many improvements, bug fixes, and high-profile API changes since then, most notably a fix for PyAV support.

I'm creating this thread to help us (maintainers and contributors) decide what minimally needs to be done, and what decisions must be made before we can proceed with a release. Actually doing a release and documenting the procedure again will make it easier to do minor releases as more work is done.

Here's what I see as the key steps:

- [x] Rebase and merge #247 since it's a nice enhancement with few or no side effects.
- [x] Even though #340 is relatively new, we should try to merge it because it's such a huge performance increase.
- [x] Fix the problem with bioformats in #330 , at least by requiring Jpype ≤ 0.6.3.
- [x] Get more help with bioformats! #301 may be obsolete, and I know almost nothing about bioformats. #318 is related and looks important. If anyone (maintainer, or contributor) knows whether this is still an important fix, it would be great to find out!
- [x] Review and merge a PR I'm preparing to update the release notes.
- [x] Publish the release and copy the relevant portions of the release instructions in the trackpy wiki.

There are other PRs that are worth attention but are probably not ready for a timely release:

- #254 looks like it's still cooking, and @danielballan may be evaluating other approaches. He can correct me if I'm wrong.
- #320 seems worthwhile but it's unclear to me how big an API change this is; it at least needs to be documented. So I'm inclined to leave it until v0.6 unless @rbnvrw wants to finish it soon.
- #316 is likewise worthwhile but needs some work. I suggest we leave it out.

Note that I am **not** (yet) volunteering to do this release! I just want us to start by getting organized. Please comment on this plan — what am I missing?

**Comment by GenevieveBuckley** [comment]
>   Get more help with bioformats! #301 may be obsolete, and I know almost nothing about bioformats. #318 is related and looks important. If anyone (maintainer, or contributor) knows whether this is still an important fix, it would be great to find out!

Yes, this is still an important fix, imo. I think the plan you've suggested on those issues sounds appropriate.

**Comment by rbnvrw** [comment]
Awesome @nkeim! Thank you for taking the time to do this.

- Regarding #247: yes, that sounds good to me. @caspervdw do you have time to update the PR maybe?
- Regarding #340: yes, though I'm a little hesitant to review it myself, as I have never used any of the PyAV functionality before.
- Regarding the Bioformats issues / PRs: @caspervdw nows more about this, he also created PR #301. If he has time to upgrade that PR, that would be great, otherwise we can try to do it. Also great that @GenevieveBuckley is helping with this! :+1: 

About my PR #320: all the work is basically done. It is just about properly documenting it in the release notes. Should I add it to #345 ?

**Comment by danielballan** [comment]
> #254 looks like it's still cooking, and @danielballan may be evaluating other approaches. He can correct me if I'm wrong.

That's right.

**Comment by rbnvrw** [comment]
Hi @nkeim I just wanted to check in with you: what is the status of this? I think most of the points are done? Do you think we're ready for a release?

**Comment by nkeim** [comment]
Yes, I think we are ready to go! Sorry I haven't been able to spend much time on this in the past few weeks. 

I put a draft of the release instructions in the wiki, based on the process for the most recent trackpy release. @rbnvrw do you want to take the lead on this? I'll have some time to help next week but probably not enough to make sure it happens.

**Comment by nkeim** [comment]
Update: v0.5 is available on PyPI! I am still waiting for the conda-forge bot to act on this. I’m headed to bed and if it hasn’t happened by morning, I’ll take care of it manually. Stay tuned…

**Comment by nkeim** [comment]
I think we're done! The conda-forge package is built and *should* be in the channel momentarily. Thanks especially to @GenevieveBuckley , @tacaswell , @jakirkham , @rbnvrw , and @caspervdw for their assistance. Please let me know if anything looks amiss!

This [wiki page](https://github.com/soft-matter/pims/wiki/Releasing-a-new-version-of-pims) is based on the trackpy instructions and will hopefully let any maintainer carry out a release in the future.

**Comment by jakirkham** [comment]
Thanks @nkeim! 😄

**Comment by danielballan** [comment]
Yes, thanks!

**Comment by rbnvrw** [comment]
Awesome, thank you @nkeim 🥇

**Comment by caspervdw** [comment]
Thanks for getting this done @nkeim!

**Comment by GenevieveBuckley** [comment]
This is great, thank you!
